### ISSUE TITLE
Automatically update whenever routes.rb is changed.

### ISSUE THREAD

**Issue by digerata** [basgren/railways#14]
Not sure if the JetBrains API allows it, but it would be so great to have railways update in the background whenever the routes file is changed.

**Comment by basgren** [comment]
Finally I released this :) Currently, the feature is experimental, so if you want to use autoupdate, please enable it in Railways settings. If you find any bugs, please feel free to report.

**Comment by digerata** [comment]
That's awesome! Trying it out now, thanks!
