### ISSUE TITLE
Use Spring for calling rake

### ISSUE THREAD

**Issue by andrey-skat** [basgren/railways#15]
Please, add option to call rake with Spring (`bin/rake`)

**Comment by basgren** [comment]
Thanks you for the suggestion! I'll take a look at it.

**Comment by basgren** [comment]
Hi @andrey-skat . I traced the process of requesting rake routes and I'm pretty sure that RubyMine API runs `bin/rake` every time you refresh routes if `rake` file is present inside your project bin directory. At least RubyMine 7 API does this.
