### ISSUE TITLE
Railsways causes the RubyMine application to pause sporadically.

### ISSUE THREAD

**Issue by stevobengtson** [basgren/railways#18]
As I am using the Railways plugin with our application I find that every few seconds to every minute the whole RubyMine application pauses and becomes unresponsive (ui is also not updated). If I disable the Railways plugin everything works as expected.

Environment:
 RubyMine (EAP) 7.1 141.373 (Though this has been happening in version 7.0 as well).
 Railways 0.8.2
 Ruby 2.1.5 with Rails 3.1.
 Routes in application: 2460

**Comment by basgren** [comment]
Thank you for letting me know! Railways periodically rechecks whether controller methods exist, so it can highlight existing methods, but I tested this feature on 10k routes and it worked smoothly.
Does it hang when you stop typing or happens occasioanlly?

Thanks.

**Comment by stevobengtson** [comment]
It happens as I am typing as well, cursor stops blinking, and UI is no longer responsive.

**Comment by basgren** [comment]
Thank you @stevobengtson . I already sent you an email with test version of the plugin where you can disable these live inspections and check if it helps.

**Comment by basgren** [comment]
Hi @stevobengtson . I have released new version of the plugin (0.8.3), where I added plugin option to disable live route action check (you've seen it already, when I sent you 0.8.3-beta), but also I updated performance of this check process and increased the delay before the check is started. So now on my PC updating of 15k routes takes about 1-2 seconds, but all consequent updates take 0.2-0.4 sec.
Please update the plugin to 0.8.3  and let me know if this issue still bothers you.
