### ISSUE TITLE
Please Copy Name for the Path Helper and the URL Helper

### ISSUE THREAD

**Issue by shingo-nakanishi** [basgren/railways#21]
"Routes" panel can not copy.
Please Copy `Name` for the Path Helper and the URL Helper to my code.
And copy Route.

**Comment by basgren** [comment]
Hi. Sorry - I was on vacation a couldn't respond.
Could you please explain the issue? Is copy functionality broken? What IDE version do you have?

**Comment by shingo-nakanishi** [comment]
Thank you respond.
this is enhancement.

RubyMine version is RubyMine8.

![copy_to_clipboad](https://cloud.githubusercontent.com/assets/2630601/12376761/db9c316a-bd47-11e5-9a19-d5a43ee7720c.png)

**Comment by basgren** [comment]
Thanks for the explanation! Will try to do something with that :)

**Comment by basgren** [comment]
I added more copy options in 0.8.4. Now you can copy route path from route table (using hotkeys or right-click) and from route info panel. From route info panel displayed value is copied as is, while from table you can copy full path (i.e. "GET /books/:id") via context menu or by pressing Ctrl + Shift + C. Also now it's possible to copy multiple rows at once.

Please let me know if it works fine for you.

**Comment by shingo-nakanishi** [comment]
@basgren Thank you!
