### ISSUE TITLE
Not working on RubyMine 2016.2.3

### ISSUE THREAD

**Issue by shibabu** [basgren/railways#26]
I'm using RubyMine 2016.2.3 / Build #RM-162.1812.23, built on September 5, 2016.
Railways does not show up at all in the tool windows.

 All other plugins I have are JetBrains ("Native") Plugins, is it working on this new build for someone else?

**Comment by basgren** [comment]
Hi! Thanks for letting me know.
Unfortunately, I will be able to check this only next week. Sorry for the
inconvenience.

**Comment by shibabu** [comment]
Same with the new 2016.2.4 build! 
Maybe I should stop updating Rubymine?

**Comment by basgren** [comment]
Hi, @shibabu . I just downloaded the most recent RubyMine 2016.2.4 (build #RM-162.2032.10, built on September 22, 2016) and Railways plugin 0.8.6 works just fine.

1. Does your IDE display any errors in Event Log tool window?
2. Do you have default Rails directory structure in your project? Routes tool window will be displayed only when IDE detects that Rails project is opened.

**Comment by shibabu** [comment]
Hi @basgren, No error on the events log. I did not expect it but when I open an old Rails project, Railways works. But not with the current project, which has the default directory structure and is a Rails Project!

**Comment by shibabu** [comment]
Issue with RubyMine instead, not recognising my project as a Rails one.
Probably it has to do with the use of rbenv for local RubySDK, but didn't investigate further and just deleted .idea/ and restarted the IDE.

Working and as addictive as useful a plugin. Thanks Basil @basgren !

**Comment by basgren** [comment]
Thank you! Glad to hear that!
Please don't hesitate to contact me if you have any issues or ideas.
