### ISSUE TITLE
Add regex support -- feature

### ISSUE THREAD

**Issue by thestelz** [basgren/railways#28]
I would like to request the feature of adding of a wild card or regex to search for a route. Currently when searching for a route, it has to be in the exact way that it's typed in the `routes.rb` file.

----

Example:

When typing `companies/` I want to add a wild card (`*`) after the slash (`/`), but if the route doesn't have the `*` in it, it doesn't match anything.

![screen shot 2017-10-20 at 4 41 26 pm](https://user-images.githubusercontent.com/1774502/31841129-28c39934-b5b6-11e7-873e-94cb02757404.png)

![screen shot 2017-10-20 at 4 41 44 pm](https://user-images.githubusercontent.com/1774502/31841138-2d8e96f8-b5b6-11e7-9545-c527596966ae.png)

![screen shot 2017-10-20 at 4 41 55 pm](https://user-images.githubusercontent.com/1774502/31841141-31a3fa94-b5b6-11e7-8c27-7afa88f48a3d.png)

----

Settings:

![screen shot 2017-10-20 at 4 44 32 pm](https://user-images.githubusercontent.com/1774502/31841146-37cef4dc-b5b6-11e7-82ae-1fae580073f4.png)

Thanks for the awesome plugin!

**Comment by thestelz** [comment]
Forgot to include info about what version I'm using:

```
RubyMine 2017.2.4
Build #RM-172.4155.44, built on September 26, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13
```

Just in case you need/want it.

**Comment by basgren** [comment]
Thank you! Will consider this feature soon.

**Comment by basgren** [comment]
Finally got my hands on it :) @thestelz feel free to check 0.8.9 version with wildcard functionality. Please let me know if you find any issues.

**Comment by thestelz** [comment]
Sweet! Thanks @basgren!!

Just downloaded it and it works like a charm!
