### ISSUE TITLE
Plugin is incompatible with RM 2018.1 EAP [bug/feature]

### ISSUE THREAD

**Issue by thestelz** [basgren/railways#31]
Just a heads up, Railways is not compatible with RubyMine 2018.1 EAP

![railways_incompatible_rm_2018 1 eap](https://user-images.githubusercontent.com/1774502/35514719-20854f24-04d5-11e8-8c97-2aaf825472b5.png)

```
RubyMine 2018.1 EAP
Build #RM-181.3007.20, built on January 25, 2018
JRE: 1.8.0_152-release-1136-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3
```

Thanks

**Comment by basgren** [comment]
Thanks for letting me know! Please check new plugin release 0.8.10 - it should be compatible with new IDE version.

**Comment by thestelz** [comment]
Working like a charm! Thanks!
