### ISSUE TITLE
Railways not supported with RM 2018.2 EAP

### ISSUE THREAD

**Issue by thestelz** [basgren/railways#33]
After updating to [RubyMine 2018.2 EAP](https://confluence.jetbrains.com/display/RUBYDEV/RubyMine+2018.2), railways no longer works.

![screen shot 2018-05-29 at 11 06 44 am](https://user-images.githubusercontent.com/1774502/40668188-dfde8a06-6331-11e8-8dee-da7e052fca4b.png)

```
RubyMine 2018.2 EAP
Build #RM-182.2574.11, built on May 23, 2018
JRE: 1.8.0_152-release-1226-b7 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3
```

Thanks!

**Comment by basgren** [comment]
Hi, @thestelz ! Thanks for pinging me!
Please check version 0.8.11. It's built for the newest 2018.2 version.
Regards!

**Comment by thestelz** [comment]
@basgren It works like a charm! Thanks for fixing!
