### ISSUE TITLE
Railways not supported in RM 2018.3 EAP

### ISSUE THREAD

**Issue by thestelz** [basgren/railways#34]
Railways is not supported in the latest EAP

```
RubyMine 2018.3 EAP
Build #RM-183.2407.12, built on September 13, 2018
JRE: 1.8.0_152-release-1293-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3
```

![railways_rm_incompatible](https://user-images.githubusercontent.com/1774502/45751640-f4448600-bbe0-11e8-838c-a43ea44893c4.png)

**Comment by basgren** [comment]
Thank you! Already working on it. Unfortunately, found one issue with routes parsing, so it might take some time.

**Comment by basgren** [comment]
I fixed the issue, but I couldn't test it well due to issue in EAP version of RubyMine: https://youtrack.jetbrains.com/issue/RUBY-22463 - I get the same thing when I try to update my routes, i.e. when I run `rake routes` using ruby mine sdk. But running the same command from plain shell outputs routes as usually. So I'd prefer to wait a couple days until they fix this issue.

**Comment by thestelz** [comment]
Thanks for the update! I have voted for that issue and hopefully they get it fixed soon!

**Comment by ddnexus** [comment]
Any news?

**Comment by basgren** [comment]
Not much, actually. While RubyMune issue is fixed (https://youtrack.jetbrains.com/issue/RUBY-22463), it's planned for RM 2018.3.1 EAP.
I still cannot run rake tasks from the most recent RubyMine 2018.3 RC (Build #RM-183.4284.98, built on November 14, 2018). I even cannot get the list of all rake tasks in "Run Rake task" popup (Ctrl + Alt + R).
@ddnexus , can you check this "run rake" popup at your side? Can you get the list of Rake tasks from RM?

**Comment by ddnexus** [comment]
Indeed I am using the RM 2018.3 RC and it would be great to have the railways too. I noticed that other plugins where not compatible with this RC. For example Git Flow and Material Theme, however I just had to uninstall and install them again, and RM picked the right version of both plugins. I did the same with railways, but now RM doesn't even list the railways plugin so I cannot install it. :/

RubyMine 2018.3
Build #RM-183.4284.98, built on November 14, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-11-generic

**Comment by basgren** [comment]
Just tested the plugin once again for stable build of RubyMine 2018.3 (Build #RM-183.4284.145, built on November 21, 2018). No luck. I even cannot get list of rake tasks using build-in RubyMine feature. So it looks like we have to wait until this fix gets into new build of RM. Without that fix Railways just won't work and I'm not sure I can fix it at my side, sorry.

**Comment by basgren** [comment]
Currently you cannot install it, sorry. Current version of the plugin is configured to be listed only for 2018.2 version of RubyMine. This is common practice to restrict installation only to IDE versions that are guaranteed to be compatible.

**Comment by thestelz** [comment]
RubyMine 2018.3.1 RC (build 183.4588.71) was just released, but doesn't appear to have your issue listed in the [release notes](https://confluence.jetbrains.com/display/RUBYDEV/RubyMine+2018.3#RubyMine2018.3-RubyMine2018.3.1RC(build183.4588.71)ReleaseNotes).

It looks like they might have a lot of [issues](https://youtrack.jetbrains.com/issue/RUBY-22949) with spring right now.

**Comment by basgren** [comment]
Good news, everyone! (C)

I've tested the plugin against new IDE versions and it seems everything is much better now: I managed to refresh rake task list and Railways also updates route list successfully.
Unfortunately, I had to set minimal supported versions for the plugin:
* RubyMine 2018.3.1 RC - **at least build #RM-183.4588.71 is required**
* IntelliJ IDEA Ultimate 2018.3.1 - **at least build 183.4588.61 is required** (tested with Ruby plugin version v2018.3.20181204)

New version 0.8.12 of Railways plugin is released, so please check it out and let me know if you have any problems with it.

And thank you guys for being so patient!

**Comment by thestelz** [comment]
It works like a charm! I so missed this plugin! Thanks for staying on top of it and waiting on JetBrains to get RM fixed!
