### ISSUE TITLE
Can't see download in RubyMine 2018.3

### ISSUE THREAD

**Issue by BaseCase** [basgren/railways#35]
Hi, thanks for making an awesome plugin!

Not sure if the problem is on RubyMine's end or Railways's, but in the latest RubyMine version, I'm unable to find the Railways plugin for download. I see in your changelog that you released a recent version of this plugin that updates it for the most recent IDE version, but for some reason, it is not showing up when I search the Marketplace.

Thanks again!

**Comment by basgren** [comment]
Hi!
It's strange, I just tested on RubyMine 2018.3.1 (Build #RM-183.4588.71, built on December 6, 2018) and I can see the plugin in marketplace. The version of IDE I specified is the minimal that is required to run the plugin. Do you have the same version installed?

**Comment by BaseCase** [comment]
Ah, that was it! I was a patch release out of date. Everything looks good now. Thank you! :)
