### ISSUE TITLE
Path within locale is not shown.

### ISSUE THREAD

**Issue by Samemura** [basgren/railways#36]
Hi I likely use railways plugin. I noticed paths are not shown under locale. Please check this below condition ? Thank you.

config/routes.rb
```
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|ja/ do
    resources :spots
``` 

result of `bundle exec rake routes`
```
spots GET        (/:locale)/spots(.:format)                                                spots#index {:locale=>/en|ja/}
```

result of `railways`
```
none
```

# Environment
Railways v0.8.12
Rubymine 2018.3.1

Ruby 2.5.1
Rails 5.1.4

**Comment by basgren** [comment]
Hi, @Samemura ! Thank you for detailed description.
Please check new version of the plugin (0.8.13) - it should work fine with optional segment in the beginning of route path.
