### ISSUE TITLE
RM 2019.1 EAP not supported

### ISSUE THREAD

**Issue by thestelz** [basgren/railways#38]
Railways is not supported in RM 2019.1 EAP.

```
RubyMine 2019.1 EAP
Build #RM-191.4212.20, built on January 22, 2019
JRE: 1.8.0_152-release-1402-b1 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13
```

**Comment by basgren** [comment]
Hi. Please check v0.8.14 of the plugin. It should work fine with RM2019.1.

**Comment by thestelz** [comment]
Works like a charm! Thanks!

BTW, love this plugin! Thank you for keeping it going! I use the crap out of it.

**Comment by basgren** [comment]
Thank you! Glad to hear that it's still used)
