### ISSUE TITLE
Copy request as curl

### ISSUE THREAD

**Issue by aristotll** [basgren/railways#39]
It will be nice to have curl support.

**Comment by basgren** [comment]
Hi. Sorry for late reply and thank you for your suggestion.
Unfortunately, I see at least two difficulties: 
* to generate valid curl, which will work right after pasting to terminal, we should know additional details, such as host, port, sometimes protocol, etc, which are available at runtime, but I believe getting this information at design time from IDE would be hard to implement.
* another my doubt - routes with URL and query parameters (like `/users/:id`) - here we also must replace parameters with valid values, and this is also not a trivial task.

So I'm closing the ticket. If you see how this feature can work in details - please feel free to describe it and reopen or create new ticket.
