### ISSUE TITLE
[Feature Request] Make the input field longer or draggable

### ISSUE THREAD

**Issue by thestelz** [basgren/railways#46]
Not a big deal by any means, but figured I would put an issue in for it. I would like to request the input field to be longer to see more of what you are typing in. It would be cool if it was draggable, but I feel like that might be overkill for what is really needed.

<img width="1424" alt="RM_RW_Routes" src="https://user-images.githubusercontent.com/1774502/97442651-75ae8c80-1900-11eb-8169-2828fc175e57.png">

From the above screenshot, there is a lot of room to extend the input field, but not sure if it's a % or a fixed width. I'm on a 15" laptop most of the time, so not sure if screen size is a big issue. Since I'm not sure what to change (as I'm not a java dev) or I would put in a pull request.

Thanks!

**Comment by basgren** [comment]
Thank you for the suggestion! I've done search field larger. I hope its size will fit your needs :)

**Comment by thestelz** [comment]
Yes, it does! Thank you!
