### ISSUE TITLE
rake routes were deprecated on rails 6.1

### ISSUE THREAD

**Issue by merkulov-ilya** [basgren/railways#50]
`rake routes` were deprecated on rails 6.1 in favor of `rails routes`: https://github.com/rails/rails/commit/41ad613e4c5d6c05f20ac0437564ff0d31ab9f5a

**Comment by thethak** [comment]
Yes, i'm facing the same issue with rails 6.1.1.

**Comment by basgren** [comment]
Hi. This issue was resolved in the newest version of the the plugin, but new version of plugin can be installed only on RubyMine 2020.3 and above. Which version of RM do you have?

**Comment by thethak** [comment]
> Hi. This issue was resolved in the newest version of the the plugin, but new version of plugin can be installed only on RubyMine 2020.3 and above. Which version of RM do you have?

Ha I'm using 2020.1 I will update. Thank you @basgren

**Comment by basgren** [comment]
Closing this ticket. If you still have the issue, please reopen it with more details.
